import { Geist } from 'next/font/google'
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className + " bg-neutral-50"}>
        {children}
      </body>
    </html>
  );
}
